#!/bin/sh

set -ex

pkg_version=$(dpkg-query -f '${Version}\n' -W pmdk-tools | sed 's/~rc/-rc/')
pkg_version=${pkg_version%-*}
echo "pmdk-tools package version: ${pkg_version}"
daxio_version=$(daxio -V)
echo "daxio version: ${daxio_version}"
if [ "$pkg_version" = "$daxio_version" ]; then
    echo "Version match, OK"
else
    echo "Version mismatch, FAIL"
    exit 1
fi
