#!/bin/sh

set -ex

arch=$(dpkg --print-architecture)

pkg_version=$(dpkg-query -f '${Version}\n' -W pmdk-tools | sed 's/~rc/-rc/')
pkg_version=${pkg_version%-*}
echo "pmdk-tools package version: ${pkg_version}"
rpmemd_version=$(rpmemd -V 2>&1 | cut -d ' ' -f 3)
echo "rpmemd version: ${rpmemd_version}"
if [ "$pkg_version" = "$rpmemd_version" ]; then
    echo "Version match, OK"
else
    echo "Version mismatch, FAIL"
    exit 1
fi
